# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_photo_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, -10, 701, 371))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("image/bg7.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.img1 = QtWidgets.QPushButton(self.centralwidget)
        self.img1.setGeometry(QtCore.QRect(70, 410, 131, 51))
        self.img1.setObjectName("img1")

        self.img2 = QtWidgets.QPushButton(self.centralwidget)
        self.img2.setGeometry(QtCore.QRect(450, 410, 131, 51))
        self.img2.setObjectName("img2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.img1.clicked.connect(self.showimage1)
        self.img2.clicked.connect(self.showimage2)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img1.setText(_translate("MainWindow", "image 1"))
        self.img2.setText(_translate("MainWindow", "image 2"))

  
    def showimage1(self):
        self.photo.setPixmap(QtGui.QPixmap("image/bg7.png"))

    def showimage2(self):
        self.photo.setPixmap(QtGui.QPixmap("image/BoBo.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_photo_2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
